version: "3"

services:
  # MongoDB service
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /var/lib/docker/volumes/mongo/_data:/data/mongo
    networks:
      - mynetwork

  # App service
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - DB_USER=root
      - DB_PASSWORD=password
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
